Large update of TrcKey API [devel]
Summary:
Completed the support of Synthetic Pos::SurvID, by making
use of the newly inserted OD::GeomSystem enum.
Allowed finding several places where the Pos::SurvID was silently
converted from/to either a boolean or Pos::GeomID.
Really marked as deprecated the functions that should no longer be
used, and updated the usage accordingly.
All existing code should compile, except for the wrong conversions
between SurvID and GeomID, which are now flagged as compilation errors,
and with one exception in the attribute engine where unsafe pointers
were used.

Test Plan:
brief testing in od_main. Random lines and poinsets show normally.
Attributes can be computed on the random line, especially the optical stack.

Reviewers: raman

Reviewed By: raman

Subscribers: nanne

Differential Revision: https://phabricator.dgbes.com:8443/D14463