od6.2: Fixed compilation errors on Windows platform;
Summary: Due to some linking errors on Windows platform isEmpty() function definition is declared in nlacrdesc.cc file.

Test Plan: Tested on Windows and Linux platforms . No errors.

Reviewers: raman

Reviewed By: raman

Differential Revision: https://phabricator.dgbes.com:8443/D12252