Added missing required desctructors [devel]
Summary:
Fixes the following error/warning
include/Basic/hiddenparam.h:181:5: error: deleting object of polymorphic class type 'Well::DisplayProperties::Log' which has non-virtual destructor might cause undefined behavior [-Werror=delete-non-virtual-dtor]

If that cannot be done, we need to find a different way to introduce the hidden parameter.

Test Plan: compiles

Reviewers: nanne

Reviewed By: nanne

Differential Revision: https://phabricator.dgbes.com:8443/D13692