Fixed compilation error.
Summary: Missing function declaration .

Test Plan: Compiles after the fix.

Reviewers: salil

Reviewed By: salil

Differential Revision: https://phabricator.dgbes.com:8443/D1319

git-svn-id: https://svn.opendtect.org/od/trunk@30480 a985855d-d384-4b45-ae33-31a410998c3c