Bug fixes and cleanup in UnitsOfMeasure and uiUnitSel [devel]
Summary:
Includes:
1- data/Mnemonics did not have the correct mnemonic for several entries
2- Made a distinction between API/%/ppm based mnemonics, to avoid straight
conversions between these incompatible types. I had to introduce a new
Mnemonic::stdType for the unit ppm
3- data/UnitsOfMeasure did not have unique symbols for the units of type 'Time'.
This is why they did not show up in the GUI, because the name and symbol must be unique
4- UnitsOfMeasure could not store a set of Mnemonic::stdType for each unit,
although such set is present in data/UnitsOfMeasure for several entries. Thus
made a TypeSet accordingly.
5- Code cleanup of UnitOfMeasure class, to hide functions only needed by
the repository
6- uiUnitSel::Setup has now a default constructor for Z-based units
7- uiUnitSel::Setup can now set if the "-*" units should be listed or not.
8- Removed unused functions in uiUnitSel

Test Plan:
Looked at the GUI for the layer properties manager, edit of UoM of well
logs, few import windows. Looking good.

Reviewers: nanne

Reviewed By: nanne

Subscribers: raman

Differential Revision: https://phabricator.dgbes.com:8443/D14293