od6.0: Solving compilation error in ArrayMath
Summary: introduced by D10713 for OD-961.

Test Plan: should work

Reviewers: helene

Reviewed By: helene

Differential Revision: https://phabricator.dgbes.com:8443/D10730