od: Removed unnecessary lines.
Summary: Assuming dpname and as->userRef() are always equal.

Test Plan: No compilation error.

Reviewers: helene

Reviewed By: helene

Differential Revision: https://phabricator.dgbes.com:8443/D1267

git-svn-id: https://svn.opendtect.org/od/trunk@30760 a985855d-d384-4b45-ae33-31a410998c3c